name = "cohere2openai"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "MY_KV_NAMESPACE"
id = "054ab2520e6a42a19a9833b986afd1f9"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
